[auth]
enabled = true
site_url = "https://brickit.build"
additional_redirect_urls = [
  "http://localhost:3000",
  "https://brickit.build",
  "https://www.brickit.build"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
